# InfisicalSecret for cluster-wide secrets replacement (follows SOPS pattern)
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
# This will be created in each namespace that includes this component
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cluster-secrets
spec:
  # For Infisical Cloud, omit hostAPI. For self-hosted, set your API endpoint:
  # hostAPI: "https://your-infisical-instance.com/api"
  resyncInterval: 60
  authentication:
    # Using Machine Identity with Universal Auth (works with private clusters)
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "security"
  # Managed secret configuration
  managedSecretReference:
    secretName: "cluster-secrets"
    # secretNamespace: inherits from the namespace where this is applied
    creationPolicy: "Orphan"