controllers:
  qbittorrent:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 20.04.1 # pinned from LinuxServer.io Docker Hub (retrieved 2024-09)
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/Los_Angeles
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 2Gi
service:
  app:
    controller: qbittorrent
    ports:
      http:
        port: 8080
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: qbittorrent.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - qbittorrent.${SECRET_TAILNET}
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  media-storage:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /media
        subPath: media
      - path: /downloads
        subPath: downloads
