controllers:
  qbittorrent:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 20.04.1 # pinned from LinuxServer.io Docker Hub (retrieved 2024-09)
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/Los_Angeles
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 2Gi
      gluetun:
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: latest
        env:
          - name: VPN_SERVICE_PROVIDER
            value: protonvpn
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_PORT_FORWARDING
            value: "on"
          - name: VPN_PORT_FORWARDING_PROVIDER
            value: protonvpn
          - name: SERVER_COUNTRIES
            value: Canada
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: "10.42.0.0/16,10.43.0.0/16"
          - name: FIREWALL_INPUT_PORTS
            value: "8080"
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: cluster-secrets
                key: WIREGUARD_PRIVATE_KEY
          - name: WIREGUARD_ADDRESSES
            valueFrom:
              secretKeyRef:
                name: cluster-secrets
                key: WIREGUARD_ADDRESSES
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      port-forward:
        dependsOn: gluetun
        image:
          repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
          tag: "1.3"
        env:
          - name: QBITTORRENT_SERVER
            value: localhost
          - name: QBITTORRENT_PORT
            value: "8080"
          - name: PORT_FORWARDED
            value: /tmp/gluetun/forwarded_port
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
service:
  app:
    controller: qbittorrent
    ports:
      http:
        port: 8080
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: qbittorrent.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - qbittorrent.${SECRET_TAILNET}
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  media-storage:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /media
        subPath: media
      - path: /downloads
        subPath: downloads
