---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      # Talos Linux requires privileged containers for TUN device access
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
            add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN"]
          runAsNonRoot: false
          runAsUser: 0
      # Talos Linux tolerations for privileged workloads
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      # Talos Linux node selector for control plane nodes
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
