---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-test
  namespace: default
  labels:
    app: storage-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-test
  template:
    metadata:
      labels:
        app: storage-test
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage-volume
              mountPath: /usr/share/nginx/html
            - name: test-file
              mountPath: /usr/share/nginx/html/test.txt
              subPath: test.txt
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-test-pvc
        - name: test-file
          configMap:
            name: storage-test-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-test-config
  namespace: default
data:
  test.txt: |
    Synology CSI Storage Test
    ========================

    This file is served from persistent storage provided by Synology CSI.

    Timestamp: $(date)

    If you can see this content, the Synology CSI storage is working correctly!

    The storage is mounted at /usr/share/nginx/html and this file is served by nginx.
---
apiVersion: v1
kind: Service
metadata:
  name: storage-test-service
  namespace: default
  labels:
    app: storage-test
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: storage-test
