---
# Generic device plugin for Talos Linux to expose /dev/net/tun device
# Required for Tailscale operator on Talos Linux 1.8.0+
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app: generic-device-plugin
spec:
  selector:
    matchLabels:
      app: generic-device-plugin
  template:
    metadata:
      labels:
        app: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: generic-device-plugin
          image: ghcr.io/squat/generic-device-plugin:latest
          args:
            - "--device"
            - |
              name: tun
              groups:
              - count: 1000
                paths:
                - path: /dev/net/tun
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
      nodeSelector:
        kubernetes.io/os: linux
  updateStrategy:
    type: RollingUpdate
