# Dify configuration for homelab deployment
global:
  # Enable migrations and sandbox
  enableMigrations: true
  enableSandbox: true

# Ingress configuration with Tailscale
ingress:
  enabled: true
  className: tailscale
  annotations: {}
  hosts:
    - host: dify.${SECRET_TAILNET}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dify-tls
      hosts:
        - dify.${SECRET_TAILNET}

# PostgreSQL configuration with Longhorn storage
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

# Redis configuration with Longhorn storage
redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Weaviate configuration with Longhorn storage
weaviate:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 32Gi

# Dify API configuration with Longhorn storage
api:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  env:
    # Reference secret for sensitive values
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: dify-env
          key: SECRET_KEY

# Dify Web configuration
web:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Worker configuration with Longhorn storage
worker:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Plugin daemon configuration with Longhorn storage
pluginDaemon:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
