---
# Grant the Coder service account (in the workspaces namespace) admin rights in the
# default namespace so workspace templates that target the default namespace
# can create/manage namespaced resources like PVCs, Deployments, Services, etc.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-admin-in-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: workspaces