---
# Grant the Coder service account admin rights in the workspaces namespace.
# This allows templates that target the workspaces namespace to create/manage
# namespaced resources like PVCs, Deployments, Services, etc.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-admin-in-workspaces
  namespace: workspaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: workspaces