controllers:
  sonarr:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.15 # pinned from LinuxServer.io Docker Hub (retrieved 2024-09)
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/Los_Angeles
        ports:
          - name: http
            containerPort: 8989
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 2Gi
service:
  app:
    controller: sonarr
    ports:
      http:
        port: 8989
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: sonarr.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - sonarr.${SECRET_TAILNET}
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /media
  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /downloads
