# InfisicalSecret for k8s-gateway secrets in network namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-gateway-infisical
  namespace: network
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "k8s-gateway-infisical"  # Name of resulting Kubernetes secret
    secretNamespace: "network"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted
