controllers:
  resume-assistant:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/yamshy/resume-assistant
          tag: 1.0.1
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: resume-assistant-env
                key: OPENAI_API_KEY
        ports:
          http:
            containerPort: 8000
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

service:
  app:
    controller: resume-assistant
    ports:
      http:
        port: 80
        targetPort: http

ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: resume-assistant.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - secretName: resume-assistant-tls
        hosts:
          - resume-assistant.${SECRET_TAILNET}

persistence:
  data:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /data
