# InfisicalSecret for portfolio-production secrets in portfolio namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: portfolio-production-infisical
  namespace: portfolio
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "portfolio-production-infisical"  # Name of resulting Kubernetes secret
    secretNamespace: "portfolio"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted
