---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 8gears
  namespace: default
spec:
  interval: 1h
  url: https://8gears.container-registry.com/library/n8n
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 1.107.4
      sourceRef:
        kind: HelmRepository
        name: 8gears
        namespace: default
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
    - kind: Secret
      name: n8n-secrets
