apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - secret.sops.yaml

configMapGenerator:
  - name: n8n-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
