controllers:
  resume-frontend:
    pod:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/yamshy/resume-assistant-ui
          tag: 1.7.1 # {"$imagepolicy": "resume-assistant:resume-assistant-ui-image-policy:tag"}
        env:
          - name: BACKEND_URL
            value: "resume-backend:8124"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - "ALL"
            add:
              - "NET_BIND_SERVICE"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
persistence:
  caddy-config:
    type: emptyDir
    globalMounts:
      - path: /config
  caddy-data:
    type: emptyDir
    globalMounts:
      - path: /data
service:
  app:
    controller: resume-frontend
    ports:
      http:
        port: 80
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: resume-assistant-ui.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - resume-assistant-ui.${SECRET_TAILNET}
