# Minimal Coder config for brokered SSH only via Tailscale Ingress.
# - Service remains ClusterIP (no NodePort/LoadBalancer)
# - Ingress uses className: tailscale (managed by Tailscale operator)
# - Host is a placeholder; update to your tailnet domain.
#
# Notes:
# - Coder defaults to brokered SSH; no extra ports/services required.
# - The chart provides in-cluster dependencies (e.g., Postgres) by default;
#   no explicit configuration is needed here for evaluation/small clusters.

service:
  type: ClusterIP

ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: coder
      paths:
        - path: /
          pathType: Prefix