# Minimal Coder config for brokered SSH only via Tailscale Ingress.
# - Service remains ClusterIP (no NodePort/LoadBalancer)
# - Ingress uses className: tailscale (managed by Tailscale operator)
#
# Notes:
# - Ccoder defaults to brokered SSH; no extra ports/services required.
# - The chart provides in-cluster dependencies (e.g., Postgres) by default;
#   no explicit configuration is needed here for evaluation/small clusters.

coder:
  env:
    - name: CODER_ACCESS_URL
      value: "https://coder.${SECRET_TAILNET}"

service:
  type: ClusterIP

ingress:
  enabled: true
  className: tailscale
  annotations: {}
  hosts:
    - host: coder.${SECRET_TAILNET}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: coder-tls
      hosts:
        - coder.${SECRET_TAILNET}

# Explicitly use Synology CSI delete StorageClass for bundled Postgres PVCs
postgres:
  default:
    storageClassName: "synology-iscsi-delete"