---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default # Required for Renovate lookups
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: ">=12.0.0 <13.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    auth:
      existingSecret: "postgresql-credentials"
      secretKeys:
        adminPasswordKey: "postgres-password"
        userPasswordKey: "postgres-password"
      database: "testdb"
    primary:
      persistence:
        enabled: true
        size: 5Gi
        storageClass: "longhorn"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      service:
        type: ClusterIP
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
