image:
  repository: ghcr.io/squat/generic-device-plugin
  tag: ""
  pullPolicy: IfNotPresent
config:
  data: |
    devices:
      - name: tun
        groups:
          - count: 1000
            paths:
              - path: /dev/net/tun
