---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-runner
  namespace: nextflow-demo
  labels:
    app.kubernetes.io/name: nextflow-runner
    app.kubernetes.io/part-of: nextflow-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-runner
  namespace: nextflow-demo
  labels:
    app.kubernetes.io/name: nextflow-runner
    app.kubernetes.io/part-of: nextflow-demo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-runner
  namespace: nextflow-demo
  labels:
    app.kubernetes.io/name: nextflow-runner
    app.kubernetes.io/part-of: nextflow-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-runner
subjects:
  - kind: ServiceAccount
    name: nextflow-runner
    namespace: nextflow-demo
