# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fPnRFGOniEoEtzm28T3RFbzw2rIvveYRSfRbeXTEIBg=,iv:bqUdSFOPnnUUE/nofi7ga2YKtM4T+3d6ZokWeAciafw=,tag:wnVmzEPoMJg7vL+bBygxgQ==,type:str]
sops:
  age:
    - recipient: age1ah5azswjpvcjylvh3w4mr0vzhrgh3dzjq7gh2jrxq5sw9789hquqt6kg6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY2FBTkVlQU0vZTdQa01t
        ZVRPYnd3dlpxREFINkx5ZU9EQXR4MHlQa2hvCkpCeHFWM0hYdmVRMHkyNWRTcDZw
        L2ZOaFEzNEozV1BzbHhLMW9hYzNublEKLS0tIDVZVDZjaEd2WjNLZXdMR2VtOU95
        N2V6TjM1TXZOUUplb3djWDg1S3c2cWMKI3vUsofkUhKDqOHdobHLMFHAIqrjQx96
        IRU9Rkcj1CvOyvnvI3V8EKK9A2PFa4wZCJoS2b1yiaoVNw5jauW+xQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-19T23:10:43Z"
  mac: ENC[AES256_GCM,data:l/JANzAAtKv0mRAlqTkeCzWfG984CDdh3bnWyyz48HX3pIfiaCNQkIflXApu7jYGaco/9ft09rhcg+o8OV69AxjPkxXilcjipj7QpYDg9sBwMNEHbu5Ks6h7kXRnblbcuzrG2w2Ph9yFXlnwzCAeybvthFClVbfmB//gOTUz+ME=,iv:U1zHr/VoPmx4gVWu7hCmJpiQsuqTm9f+oQohosJFAmE=,tag:DcKgiHvtqCuFKhYp5apcRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
