---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app temporal
  namespace: &namespace resume-assistant
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: secrets
      namespace: resume-assistant
    - name: infisical-secrets-operator
      namespace: infisical-system
  interval: 1h
  path: ./kubernetes/apps/resume-assistant/temporal/app
  postBuild:
    substituteFrom:
      - name: resume-assistant-env
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
