---
driver:
  enabled: true
  kind: modern_ebpf
  loader:
    enabled: false

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

falcosidekick:
  enabled: true
  webui:
    enabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations: {}
      hosts:
        - host: falco-ui
          paths:
            - path: /
