---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This kustomization filters the upstream repo to only include workflow ConfigMaps.
# At runtime, Flux syncs from: https://github.com/yamshy/nextflow-k8s-service
# We explicitly exclude deployment.yaml, service.yaml, rbac.yaml, and configmap.yaml
# to avoid conflicts with the HelmRelease-managed resources.
resources:
  - workflow-configmap.yaml
