---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dify
  namespace: ai
spec:
  interval: 1h
  url: https://borispolonsky.github.io/dify-helm

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dify
spec:
  interval: 1h
  chart:
    spec:
      chart: dify/dify
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: dify
        namespace: ai
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: dify-values
      valuesKey: values.yaml
