---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/common
resources:
  - ./kube-prometheus-stack/ks.yaml
patchesStrategicMerge:
  - ./kube-prometheus-stack/patches/prometheus-service-patch.yaml
  - ./kube-prometheus-stack/patches/alertmanager-service-patch.yaml
