# InfisicalSecret for resume-assistant secrets in ai namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: resume-assistant-env
  namespace: ai
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "resume-assistant-env"  # Name of resulting Kubernetes secret
    secretNamespace: "ai"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted
