# InfisicalSecret custom resource following official Infisical documentation
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: &app example-infisical-secret
  namespace: &namespace security
spec:
  # For Infisical Cloud, omit hostAPI. For self-hosted, set your API endpoint:
  # hostAPI: "https://your-infisical-instance.com/api"
  resyncInterval: 10
  authentication:
    # Using Machine Identity with Universal Auth (works with private clusters)
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: *namespace
  # Managed secret configuration
  managedSecretReference:
    secretName: "example-managed-secret"
    secretNamespace: *namespace
    creationPolicy: "Orphan"
