---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-test
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/apps/default/storage-test/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: storage-test
      namespace: default
  dependsOn:
    - name: synology-csi
      namespace: flux-system
