---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextflow-work-pvc
  namespace: nextflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
