---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-orchestrator-role
  namespace: nextflow
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
