---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextflow-demo
components:
  - ../../components/common
resources:
  - ./nextflow/ks.yaml
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nextflow-demo
        labels:
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/audit-version: latest
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: latest
          pod-security.kubernetes.io/warn: restricted
          pod-security.kubernetes.io/warn-version: latest
