controllers:
  resume-assistant:
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/yamshy/resume-assistant
          tag: 1.18.3 # {"$imagepolicy": "resume-assistant:resume-assistant-image-policy:tag"}
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: resume-assistant-env
                key: OPENAI_API_KEY
          - name: TEMPORAL_HOST
            value: temporal-frontend.resume-assistant.svc.cluster.local:7233
          - name: TEMPORAL_NAMESPACE
            value: default
        ports:
          - name: http
            containerPort: 8124
            protocol: TCP
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - "ALL"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
service:
  app:
    controller: resume-assistant
    ports:
      http:
        port: 8124
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: resume.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - resume.${SECRET_TAILNET}
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /data
