---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imagepolicy-image-v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: portfolio
spec:
  imageRepositoryRef:
    name: portfolio
  policy:
    semver:
      range: '>=2.0.0'
