---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: graphiti
  namespace: ai # Required for Renovate lookups
spec:
  interval: 1h
  url: https://kiberonlabs.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app graphiti
  namespace: ai
spec:
  interval: 1h
  chart:
    spec:
      chart: graphiti-mcp
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: graphiti
        namespace: ai
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: graphiti-values
      valuesKey: values.yaml
