fullnameOverride: temporal

# Disable Elasticsearch to avoid Java/cgroup compatibility issues
elasticsearch:
  enabled: false

# Disable Cassandra
cassandra:
  enabled: false

# Enable PostgreSQL for persistence
postgresql:
  enabled: true
  auth:
    username: temporal
    password: temporal
    database: temporal
  primary:
    persistence:
      size: 10Gi
    initdb:
      scripts:
        create-visibility-db.sql: |
          CREATE DATABASE temporal_visibility;
          GRANT ALL PRIVILEGES ON DATABASE temporal_visibility TO temporal;

# Configure Temporal server
server:
  replicaCount: 1
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      default:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-postgresql
          port: 5432
          database: temporal
          user: temporal
          password: temporal
      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-postgresql
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal

# Disable Prometheus monitoring to reduce complexity
prometheus:
  enabled: false

# Disable Grafana
grafana:
  enabled: false
