# Temporal Helm values for resume-assistant namespace
# Workaround for Helm chart validation bug

# Disable Cassandra but provide dummy port to satisfy validation
cassandra:
  enabled: false
  config:
    port: 9042  # Dummy value to satisfy validation

# Disable Elasticsearch - not needed for basic setup
elasticsearch:
  enabled: false

# PostgreSQL configuration (bundled)
postgresql:
  enabled: true
  auth:
    postgresPassword: "temporal"
    username: "temporal"
    password: "temporal"
    database: "temporal"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn

# SQL configuration for Temporal server
sql:
  driver: "sql"
  host: "temporal-postgresql"
  port: 5432
  database: temporal
  user: temporal
  password: temporal

# Temporal server configuration
server:
  image:
    tag: "1.24.0"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Temporal UI configuration
ui:
  enabled: true
  image:
    tag: "2.24.0"
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Temporal worker configuration
worker:
  enabled: true
  image:
    tag: "1.24.0"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Temporal admin tools
adminTools:
  enabled: true
  image:
    tag: "1.24.0"

# Service configuration
service:
  type: ClusterIP
  ports:
    frontend:
      port: 7233
      targetPort: 7233
    ui:
      port: 8080
      targetPort: 8080

# Ingress for Temporal UI
ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: temporal.${SECRET_TAILNET}
      paths:
        - path: /
          pathType: Prefix
          service:
            name: temporal-ui
            port: 8080
  tls:
    - hosts:
        - temporal.${SECRET_TAILNET}
