---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./dify/ks.yaml
  - ./neo4j-graphiti/ks.yaml
  - ./graphiti/ks.yaml
