---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app portfolio-staging
  namespace: &namespace portfolio
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: infisical-secrets-operator
      namespace: infisical-system
  interval: 1h
  path: ./kubernetes/apps/portfolio/portfolio-staging/app
  postBuild:
    substituteFrom:
      - name: portfolio-staging-infisical
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
