# InfisicalSecret for Longhorn UI ingress variables in storage namespace
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: longhorn-infisical
  namespace: storage
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"
  managedSecretReference:
    secretName: "longhorn-infisical"
    secretNamespace: "storage"
    creationPolicy: "Orphan"
    template:
      includeAllSecrets: false
      data:
        SECRET_TAILNET: "{{ .SECRET_TAILNET.Value }}"
