apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: &app app-template
spec:
  interval: 5m
  ref:
    tag: 4.2.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextflow-k8s-service
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serviceAccount:
      nextflow-sa: {}
    controllers:
      nextflow-k8s-service:
        strategy: RollingUpdate
        serviceAccount:
          identifier: nextflow-sa
        containers:
          app:
            image:
              repository: ghcr.io/yamshy/nextflow-k8s-service
              tag: 1.9.2 # {"$imagepolicy": "nextflow:nextflow-k8s-service-image-policy:tag"}
            env:
              PORT: &port 8000
              KUBECONFIG_PATH: /var/run/secrets/kubernetes.io/serviceaccount
              NEXTFLOW_IMAGE: nextflow/nextflow:25.04.7
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
    service:
      app:
        controller: nextflow-k8s-service
        ports:
          http:
            port: 80
            targetPort: *port
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
    serviceMonitor:
      app:
        enabled: false
        endpoints:
          - port: http
