---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imagerepository-source-v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nextflow-k8s-service-image
spec:
  image: ghcr.io/yamshy/nextflow-k8s-service
  interval: 5m