# InfisicalSecret for nextflow-k8s-service secrets in nextflow namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nextflow-k8s-service-infisical
  namespace: nextflow
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/nextflow-k8s-service"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "nextflow-k8s-service-infisical"  # Name of resulting Kubernetes secret
    secretNamespace: "nextflow"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted