# InfisicalSecret for cert-manager secrets in cert-manager namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "cert-manager-secret"  # Name of resulting Kubernetes secret
    secretNamespace: "cert-manager"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted