controllers:
  resume-backend:
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/yamshy/resume-assistant
          tag: 1.18.2 # {"$imagepolicy": "resume-assistant:resume-assistant-image-policy:tag"}
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: resume-assistant-env
                key: OPENAI_API_KEY
          - name: TEMPORAL_HOST
            value: temporal-frontend:7233
        ports:
          - name: http
            containerPort: 8124
            protocol: TCP
        command:
          - /bin/sh
          - -c
          - |
            uvicorn app.api:app --host 0.0.0.0 --port 8124 &
            python worker.py || echo "Worker failed, continuing with API server"
            wait
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - "ALL"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
service:
  app:
    ports:
      http:
        port: 8124
        protocol: TCP
        targetPort: 8124
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /data
