---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/n8n/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: n8n
  #     namespace: default
  decryption:
    provider: sops
    secretRef:
      name: sops-age
