controllers:
  prowlarr:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 2.0.5.5160-ls128 # Prowlarr 2.0.5 (2025-10-08)
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/Los_Angeles
        ports:
          - name: http
            containerPort: 9696
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
service:
  app:
    controller: prowlarr
    ports:
      http:
        port: 9696
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: prowlarr.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - prowlarr.${SECRET_TAILNET}
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  media-storage:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /media
        subPath: media
      - path: /downloads
        subPath: downloads
