# Deploy Qdrant MCP server using bjw-s app-template
controllers:
  mcp:
    strategy: RollingUpdate
    replicas: 1
    containers:
      app:
        image:
          # Official GHCR image for Qdrant MCP server
          repository: ghcr.io/qdrant/mcp-server-qdrant
          tag: latest
        env:
          # FastMCP server settings
          FASTMCP_HOST: 0.0.0.0
          FASTMCP_PORT: "8000"
          # Qdrant connection
          QDRANT_URL: http://qdrant.ai.svc.cluster.local:6333
          # QDRANT_API_KEY: ${QDRANT_API_KEY}
          COLLECTION_NAME: mcp-memory
        ports:
          - name: http
            containerPort: 8000
        probes:
          liveness:
            enabled: true
            type: TCP
            port: http
          readiness:
            enabled: true
            type: TCP
            port: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
service:
  app:
    controller: mcp
    ports:
      http:
        port: 8000
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: qdrant-mcp.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - qdrant-mcp.${SECRET_TAILNET}