---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: storage
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: storage
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Enable persistence for Longhorn UI
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2

    # Enable metrics for monitoring
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s

    # Default settings for Longhorn
    defaultSettings:
      # Create default disk on labeled nodes
      createDefaultDiskLabeledNodes: true
      # Default replica count for volumes
      defaultReplicaCount: 2
      # Default data path for volumes
      defaultDataPath: /var/lib/longhorn
      # Enable offline replica rebuilding
      offlineReplicaRebuilding: true
      # Storage over-provisioning percentage
      storageOverProvisioningPercentage: 100
      # Concurrent backup restore per node limit
      concurrentBackupRestorePerNodeLimit: 5
      # Snapshot max count
      snapshotMaxCount: 250

    # Priority class for Longhorn pods
    priorityClass:
      enabled: true
      value: 1000000000

    # UI settings
    ui:
      enabled: true
      replicas: 2
      # Service type for the UI
      service:
        type: ClusterIP

    # Tailscale ingress for Longhorn UI
    ingress:
      enabled: true
      host: longhorn.${SECRET_TAILNET}
      path: /
      pathType: Prefix
      ingressClassName: tailscale
      annotations: {}
      tls: true
      tlsSecret: longhorn-tls

    # CSI settings for high availability
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3

    # Manager settings
    longhornManager:
      log:
        format: plain
      priorityClass: "longhorn-critical"

    # Driver settings
    longhornDriver:
      log:
        format: plain
      priorityClass: "longhorn-critical"

    # Pre-upgrade checker (disable for GitOps)
    preUpgradeChecker:
      jobEnabled: false
      upgradeVersionCheck: false
