---
apiVersion: v1
kind: Node
metadata:
  name: homelab-01
  labels:
    node.longhorn.io/create-default-disk: "config"
  annotations:
    node.longhorn.io/default-disks-config: '[{"path":"/var/lib/longhorn","allowScheduling":true}]'
---
apiVersion: v1
kind: Node
metadata:
  name: homelab-02
  labels:
    node.longhorn.io/create-default-disk: "config"
  annotations:
    node.longhorn.io/default-disks-config: '[{"path":"/var/lib/longhorn","allowScheduling":true}]'
---
apiVersion: v1
kind: Node
metadata:
  name: homelab-03
  labels:
    node.longhorn.io/create-default-disk: "config"
  annotations:
    node.longhorn.io/default-disks-config: '[{"path":"/var/lib/longhorn","allowScheduling":true}]'
