---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-chart
  namespace: storage
spec:
  interval: 10m
  url: https://christian-schlichtherle.github.io/synology-csi-chart
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: synology-csi
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: synology-csi-chart
        namespace: storage
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  timeout: 10m0s
  values:
    clientInfoSecret:
      name: client-info-secret

    # StorageClasses will be created explicitly in separate manifests
    # This prevents template errors by not providing the storageClasses section
