apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  namespace: storage
type: Opaque
stringData:
  client-info.yaml: ENC[AES256_GCM,data:WPJLwP01h/smYluR70wuAM/ajwbIWBL6vM+2j+R5d+aBxs/VN68/ADufNhjyOvNkujjrB5QSIKvx9FOiamY77mlno52SqW9+NlvcKctRVgWy7bgZKFyonf2yuTjN8sRN7TTyG5bnDoYbb0vce/K0hvoC0KPhNm9E9Wd5PKg7XUV/q6RdJAidC9Jh989rKu1CsfgnxU7czmPuIu5GhnzETmQ+lzfqpcZTDwuKgUI00Dmu4F3gLyiANq2jcLiJT/L2h774H/AyTC+lshSRyfBtx3ifL8I/lSxAikFRvcwWxqzfx8YrutQrJPfz3J2XkkP3p/b9S73eaU0=,iv:fPIQ8BMAKWg80fFQwLY8SEnnqkr9OUzgd+UblN9OVCc=,tag:DOyujrAz+eGsprYNjllDDg==,type:str]
sops:
  age:
    - recipient: age1ah5azswjpvcjylvh3w4mr0vzhrgh3dzjq7gh2jrxq5sw9789hquqt6kg6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNzJWdk1aeFBQMmp1eG9i
        UnR2TDVVMXBrdXh6Mk1YNFZ6aUZ5UmpGelRJCldWZGM4S0JkaWRLL0U0UFgzOEdr
        eUFZN0Vram1GTUZzejBGNzg2SnZHQjQKLS0tIEhtaS80emFFWlZMaW1ZSTR1Qk9I
        Q1B2MG5FNzZXRi9Ha0RHcW9lM1lHTlUKG0d0KceVOwp4UHOvCvizNwrlb1tizp56
        Nn/DZRri4ilOEXRGseWS+enh3k+e0u4vMGde3bGmsflAKupFiZHgGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-31T00:44:25Z"
  mac: ENC[AES256_GCM,data:QawhX43l1tnw2VB/BPtLUUbCSPVrBlpw5V03wrN8slDbz1rOF5QBHcoa5rbv/fjRlni1dlT1bOgVByAfpIoq5DCTJ6028ZSf1vOVXOgy+Cle5FbY+x4R4kCfdm5KlPk64R9eHhNVsebckI5pkD9PUdUT9tjZmBVHpyPGwbYg5oo=,iv:TfT+AZlZE+6ywe6Fi9mEsj4A41feykDopOwVaXNSUH4=,tag:A6zgGakzjnp3jzHYV5m39w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
