---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agixt
  namespace: agents
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      agixt:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/josh-xt/agixt
              tag: latest
            envFrom:
              - configMapRef:
                  name: agixt-config
              - secretRef:
                  name: agixt-secrets
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3437
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 2Gi
              limits:
                memory: 8Gi
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-iscsi-delete
        globalMounts:
          - path: /agixt/models
    service:
      app:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: agixt
        ports:
          http:
            port: 7437
          web:
            port: 3437
