---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: network
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: network
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth-secret
      valuesKey: oauth
  values:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
    podSecurityContext:
      fsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
    serviceAccount:
      create: true
    rbac:
      create: true
