---
# Tailscale ProxyClass for Talos Linux compatibility
# Requests the tun device resource from the generic device plugin
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-tun
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - NET_RAW
