---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
components:
  - ../../components/common
resources:
  - ./portfolio-home/ks.yaml
