controllers:
  bazarr:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/bazarr
          tag: v1.5.3-ls321 # Bazarr 1.5.3 (2025-10-07)
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: America/Los_Angeles
        ports:
          - name: http
            containerPort: 6767
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
service:
  app:
    controller: bazarr
    ports:
      http:
        port: 6767
        protocol: TCP
        targetPort: http
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: bazarr.${SECRET_TAILNET}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - bazarr.${SECRET_TAILNET}
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  media-storage:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-storage
    globalMounts:
      - path: /media
        subPath: media
      - path: /downloads
        subPath: downloads
