---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: util
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: protonmail-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: protonmail-bridge
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: protonmail-bridge
          image: shenxn/protonmail-bridge:latest
          env:
            - name: BRIDGE_MODE
              value: "combined"
          ports:
            - name: smtp
              containerPort: 1025
              protocol: TCP
            - name: imap
              containerPort: 1143
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 0
            runAsGroup: 0
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: protonmail-data
              mountPath: /root
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: protonmail-bridge-data
