---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: util
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: protonmail-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: protonmail-bridge
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: protonmail-bridge
          image: shenxn/protonmail-bridge:latest
          env:
            - name: BRIDGE_MODE
              value: "combined"
            - name: BRIDGE_DEBUG
              value: "1"
            - name: BRIDGE_HEADLESS
              value: "false"
          ports:
            - name: smtp
              containerPort: 1025
              protocol: TCP
            - name: imap
              containerPort: 1143
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: protonmail-data
              mountPath: /root
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: protonmail-bridge-data
