---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: util
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: protonmail-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: protonmail-bridge
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      labels:
        app.kubernetes.io/name: protonmail-bridge
      containers:
        - name: protonmail-bridge
          image: shenxn/protonmail-bridge:latest
          env:
            - name: BRIDGE_MODE
              value: "combined"
            - name: BRIDGE_DEBUG
              value: "1"
            - name: BRIDGE_HEADLESS
              value: "false"
            - name: RESTART_TIMESTAMP
              value: "2025-08-21T21:50:00Z"
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
          # Remove problematic probes for now - they prevent the pod from starting
          # until the bridge is initialized
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 0
            runAsGroup: 0
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: protonmail-data
              mountPath: /protonmail-data
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: protonmail-bridge-data
