---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: truecharts
  namespace: util
spec:
  interval: 1h
  url: https://charts.truecharts.org
  type: oci
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app protonmail-bridge
  namespace: util
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/part-of: homelab
spec:
  interval: 5m
  chart:
    spec:
      chart: protonmail-bridge
      version: "17.3.2"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: util
  values:
    # Image configuration
    image:
      repository: docker.io/shenxn/protonmail-bridge
      tag: "3.19.0-1@sha256:3717b4441130675dc9131196de9f9c5287d2ea21b138d83b0486429e1737638a"

    # Security context configuration
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    # Service configuration - disable main service, enable SMTP and IMAP separately
    service:
      main:
        enabled: false
      smtp:
        enabled: true
        primary: true
        type: LoadBalancer
        loadBalancerClass: tailscale
        ports:
          smtp:
            enabled: true
            primary: true
            port: 1025  # External port for SMTP
            protocol: tcp
            targetPort: 25  # Internal container port
      imap:
        enabled: true
        type: LoadBalancer
        loadBalancerClass: tailscale
        ports:
          imap:
            enabled: true
            port: 1143  # External port for IMAP
            protocol: tcp
            targetPort: 143  # Internal container port

    # Persistence configuration using Longhorn
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
        mountPath: "/root"  # Correct mount path for TrueCharts

    # Environment variables for bridge configuration
    env:
      - name: BRIDGE_MODE
        value: "combined"
      - name: BRIDGE_DEBUG
        value: "1"
      - name: BRIDGE_HEADLESS
        value: "false"
      - name: RESTART_TIMESTAMP
        value: "2025-08-21T21:50:00Z"

    # Resource limits and requests
    resources:
      main:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
