---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-data
  namespace: util
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uses default Longhorn storage class
