---
apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge
  namespace: util
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: homelab
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
      protocol: TCP
    - name: imap
      port: 1143
      targetPort: imap
      protocol: TCP
  selector:
    app.kubernetes.io/name: protonmail-bridge
