---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: generic-device-plugin
  namespace: kube-system
spec:
  interval: 1h
  url: https://charts.gabe565.com
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: generic-device-plugin
      version: "0.1.3"
      sourceRef:
        kind: HelmRepository
        name: generic-device-plugin
        namespace: kube-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: generic-device-plugin-values
      valuesKey: values.yaml
