---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: kubeconform-validate

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  KUBE_VERSION: "1.33.4"
  SECRET_DOMAIN: "example.com"
  PORTFOLIO_DOMAIN: "portfolio.example.com"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install kustomize (v5.7.0)
        env:
          KUSTOMIZE_VERSION: v5.7.0
          KUSTOMIZE_SHA256: 0d98f06d6d2c2c0ff8923cc136a517af74aaa187f1b9f3e17ff370d0625ede84
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -fsSL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz" -o "${tmpdir}/kustomize.tar.gz"
          echo "${KUSTOMIZE_SHA256}  ${tmpdir}/kustomize.tar.gz" | sha256sum -c -
          tar -xzf "${tmpdir}/kustomize.tar.gz" -C "${tmpdir}" kustomize
          sudo install -m 0755 "${tmpdir}/kustomize" /usr/local/bin/kustomize
          kustomize version

      - name: Install kubeconform (v0.7.0)
        env:
          KUBECONFORM_VERSION: v0.7.0
          KUBECONFORM_SHA256: c31518ddd122663b3f3aa874cfe8178cb0988de944f29c74a0b9260920d115d3
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -fsSL "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" -o "${tmpdir}/kubeconform.tar.gz"
          echo "${KUBECONFORM_SHA256}  ${tmpdir}/kubeconform.tar.gz" | sha256sum -c -
          tar -xzf "${tmpdir}/kubeconform.tar.gz" -C "${tmpdir}" kubeconform
          sudo install -m 0755 "${tmpdir}/kubeconform" /usr/local/bin/kubeconform
          kubeconform -v
      - name: Install yq (v4.44.1)
        env:
          YQ_VERSION: v4.44.1
          YQ_SHA256: 2320004a2deaa51c9ecd8374dd3ac8f5db47dd5ce017aa203e83a41104e73eff
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -fsSL "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64.tar.gz" -o "${tmpdir}/yq.tar.gz"
          echo "${YQ_SHA256}  ${tmpdir}/yq.tar.gz" | sha256sum -c -
          tar -xzf "${tmpdir}/yq.tar.gz" -C "${tmpdir}"
          sudo install -m 0755 "${tmpdir}/yq_linux_amd64" /usr/local/bin/yq
          yq --version

      - name: Build overlay list
        id: overlays
        shell: bash
        run: |
          mapfile -t OVERLAYS < <(
            git ls-files | grep -E '/kustomization\.ya?ml$' | xargs -n1 dirname | sort -u \
              | grep -F -v -f <(sed 's#\*\*/##g; s#/\*\*##g' .kubeconformignore)
          )
          if [ ${#OVERLAYS[@]} -eq 0 ]; then
            echo "No kustomize overlays found."; exit 1
          fi
          printf '%s\n' "${OVERLAYS[@]}" > overlays.txt
          echo "count=${#OVERLAYS[@]}" >> $GITHUB_OUTPUT

      - name: Validate with kubeconform (strict)
        shell: bash
        run: |
          SKIP_KINDS="HelmRepository,Bucket,HelmChart,ImageRepository,ImagePolicy,ImageUpdateAutomation,InfisicalSecret"
          while read -r overlay; do
            echo "::group::Validate ${overlay}"
            kustomize build "${overlay}" \
              | envsubst \
              | yq eval 'del(.sops)' - \
              | kubeconform \
                  -strict \
                  -summary \
                  -kubernetes-version "${KUBE_VERSION}" \
                  -schema-location default \
                  -schema-location "${GITHUB_WORKSPACE}/schemas/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" \
                  -schema-location "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" \
                  -skip "${SKIP_KINDS}"
            echo "::endgroup::"
          done < overlays.txt

      - name: Report overlay count
        run: echo "Validated ${{ steps.overlays.outputs.count }} overlays."
