name: Shell and Talos lint
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          set -euo pipefail
          mapfile -t files < <(git ls-files 'scripts/**/*.sh')
          if [ "${#files[@]}" -eq 0 ]; then
              echo "No shell scripts to lint."
              exit 0
          fi
          shellcheck "${files[@]}"

  talhelper-validate:
    name: Talhelper validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install talhelper
        env:
          TALHELPER_VERSION: v3.0.35
          TALHELPER_SHA256: 44a33a5ebe2ee63e3bdafa9ec4633bf48adc7c365d68b88d04f2bc6b0126db5b
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          curl -sSL "https://github.com/budimanjojo/talhelper/releases/download/${TALHELPER_VERSION}/talhelper_linux_amd64.tar.gz" -o "${tmpdir}/talhelper.tar.gz"
          echo "${TALHELPER_SHA256}  ${tmpdir}/talhelper.tar.gz" | sha256sum -c -
          tar -xzf "${tmpdir}/talhelper.tar.gz" -C "${tmpdir}" talhelper
          sudo install -m 0755 "${tmpdir}/talhelper" /usr/local/bin/talhelper
      - name: Validate Talos configuration
        run: talhelper validate talconfig talos/talconfig.yaml --env-file talos/talenv.yaml
