name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  node:
    if: ${{ hashFiles('**/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Run tests
        run: |
          npm test --if-present

  python:
    if: ${{ hashFiles('**/pyproject.toml', '**/requirements.txt') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install . || true; fi
          pip install pytest
      - name: Run tests (pytest if tests found)
        run: |
          if git ls-files | grep -E '(^|/)(tests/|test_.*\\.py|.*_test\\.py)' >/dev/null; then \
            pytest -q; \
          else \
            echo "No Python tests detected"; \
          fi

  go:
    if: ${{ hashFiles('**/go.mod') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test ./...

  rust:
    if: ${{ hashFiles('**/Cargo.toml') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --all

  make:
    if: ${{ hashFiles('**/Makefile') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests via Makefile
        run: make test
