---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: trufflehog-secrets-scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  trufflehog:
    name: TruffleHog OSS Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Scan repository for secrets
        uses: trufflesecurity/trufflehog@d411fff7b8879a62509f3fa98c07f247ac089a51 # v3.95.5
        with:
          path: ./
          extra_args: --only-verified