---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: trufflehog-secrets-scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  trufflehog:
    name: TruffleHog OSS Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0

      - name: Scan repository for secrets
        uses: trufflesecurity/trufflehog@bcfcf73aaf4759d4dadc2783177c245a02792318 # v3.97.0
        with:
          path: ./
          extra_args: --only-verified