# InfisicalSecret for cilium-gateway secrets in kube-system namespace
# Reference: https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cilium-infisical
  namespace: kube-system
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homelab-0r-b1"
        envSlug: "prod"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "kube-system"  # Infrastructure credentials
  managedSecretReference:
    secretName: "cilium-infisical"  # Name of resulting Kubernetes secret
    secretNamespace: "kube-system"
    creationPolicy: "Orphan"  # Keep secret if InfisicalSecret is deleted
